import 'package:flutter/material.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Rectangle1Widget1.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Small4Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Rectangle4Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Rectangle1Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/List2Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Liat4samWidget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/SamsonNegashWidget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/List1Widget1.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Rectangle3Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/List1Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Small1Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Rectangle2Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Small2Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/List3Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Rectangle5Widget.dart';
import 'package:flutterapp/figma/iphone11promax1widget/widgets/Small3Widget.dart';

/* Frame iPhone 11 Pro Max - 1
    Autogenerated by FlutLab FTF Generator
  */
class IPhone11ProMax1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 414.0,
      height: 896.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child:
            Stack(fit: StackFit.expand, alignment: Alignment.center, children: [
          Container(
            width: null,
            height: null,
            decoration: BoxDecoration(
              color: Color.fromARGB(255, 247, 240, 240),
            ),
            child: null,
          ),
          Positioned(
            left: 18.0,
            top: 528.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 66.0,
            child: Small4Widget(),
          ),
          Positioned(
            left: 18.0,
            top: 643.0,
            right: null,
            bottom: null,
            width: 378.0,
            height: 67.0,
            child: Rectangle4Widget(),
          ),
          Positioned(
            left: 19.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 378.0,
            height: 67.0,
            child: Rectangle1Widget(),
          ),
          Positioned(
            left: 0.0,
            top: 0.0,
            right: null,
            bottom: null,
            width: 414.0,
            height: 230.0,
            child: Rectangle1Widget1(),
          ),
          Positioned(
            left: 19.0,
            top: 381.0,
            right: null,
            bottom: null,
            width: 378.0,
            height: 67.0,
            child: Rectangle2Widget(),
          ),
          Positioned(
            left: 19.0,
            top: 382.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 66.0,
            child: Small2Widget(),
          ),
          Positioned(
            left: 47.0,
            top: 158.0,
            right: null,
            bottom: null,
            width: 367.0,
            height: 107.0,
            child: SamsonNegashWidget(),
          ),
          Positioned(
            left: 19.0,
            top: 527.0,
            right: null,
            bottom: null,
            width: 378.0,
            height: 67.0,
            child: Rectangle3Widget(),
          ),
          Positioned(
            left: 109.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 67.0,
            child: List1Widget(),
          ),
          Positioned(
            left: 19.0,
            top: 265.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 66.0,
            child: Small1Widget(),
          ),
          Positioned(
            left: 19.0,
            top: 645.0,
            right: null,
            bottom: null,
            width: 16.0,
            height: 66.0,
            child: Small3Widget(),
          ),
          Positioned(
            left: 20.0,
            top: 527.0,
            right: null,
            bottom: null,
            width: 15.0,
            height: 67.0,
            child: Rectangle5Widget(),
          ),
          Positioned(
            left: 109.0,
            top: 264.0,
            right: null,
            bottom: null,
            width: 224.0,
            height: 67.0,
            child: List1Widget1(),
          ),
          Positioned(
            left: 98.0,
            top: 393.0,
            right: null,
            bottom: null,
            width: 201.0,
            height: 55.0,
            child: List2Widget(),
          ),
          Positioned(
            left: 96.0,
            top: 528.0,
            right: null,
            bottom: null,
            width: 237.0,
            height: 53.0,
            child: List3Widget(),
          ),
          Positioned(
            left: 86.0,
            top: 647.0,
            right: null,
            bottom: null,
            width: 269.0,
            height: 64.0,
            child: Liat4samWidget(),
          )
        ]),
      ),
    ));
  }
}
