import 'package:flutter/material.dart';

/* Text List 3
    Autogenerated by FlutLab FTF Generator
  */
class List3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''List 3''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 45.0,
        fontFamily: 'Reem Kufi',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 0, 0, 0),
        /* letterSpacing: 2.6999999999999997, */
      ),
    );
  }
}
