import 'package:flutter/material.dart';

/* Text Samson Negash
    Autogenerated by FlutLab FTF Generator
  */
class SamsonNegashWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Text(
      '''Samson Negash''',
      overflow: TextOverflow.visible,
      textAlign: TextAlign.left,
      style: TextStyle(
        height: 1.171875,
        fontSize: 45.0,
        fontFamily: 'Reem Kufi',
        fontWeight: FontWeight.w400,
        color: Color.fromARGB(255, 249, 22, 50),
        /* letterSpacing: 2.6999999999999997, */
      ),
    );
  }
}
