import 'package:flutter/material.dart';

/* Rectangle small 4
    Autogenerated by FlutLab FTF Generator
  */
class Small4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Container(
      width: 16.0,
      height: 66.0,
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: null,
          height: null,
          decoration: BoxDecoration(
            color: Color.fromARGB(255, 49, 23, 103),
          ),
          child: null,
        ),
      ),
    );
  }
}
